name: Run Python Matrix App

on:
  push:
    branches:
      - main  # Triggers the workflow when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger when a PR is created or updated on the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub's hosted Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4  # Sets up Python for the environment
      with:
        python-version: '3.8'  # Choose the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install required packages

    - name: Run the Python app
      run: |
        python app.py  # Run your Python script
